sudo: false
language: python
python:
  - '3.6'
  - '3.7'
  - '3.8'
  - 'pypy'
  - 'pypy3'

install:
  - make

script:
  - make ci

cache: pip

jobs:
  include:
    - stage: test
      script: make ci
    - stage: coverage
      python: 3.7
      script: codecov
